language: go
sudo: required
go:
  - 1.6
script:
  - ./scripts/build.sh
after_success:
  - gcloud --version
  - gsutil --version
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
