language: go
sudo: required
dist: trusty
go:
  - 1.6
before_install:
  - openssl aes-256-cbc -K $encrypted_8b284018d0bb_key -iv $encrypted_8b284018d0bb_iv -in gcp-travisci.json.enc -out gcp-travisci.json -d
  - echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update -qq && sudo apt-get install google-cloud-sdk
  - gcloud auth activate-service-account --key-file gcp-travisci.json
install:
  - gcloud config set project project-kel
  - ./scripts/deps.sh
script:
  - ./scripts/build.sh
after_success:
  - ./scripts/deploy.sh
